### ISSUE TITLE
ValueError: substring not found

### ISSUE THREAD

**Issue by cdubiel08** [abtExp/doccano_to_bilou#1]
```
$ python convert.py download.jsonl
Traceback (most recent call last):
  File "convert.py", line 154, in <module>
    convert_to_bilou(file_name)
  File "convert.py", line 148, in convert_to_bilou
    with open(jsonl_file[:jsonl_file.rindex('/')+1]+'annotation_iob.json', 'w') as f:
ValueError: substring not found
```
The .jsonl format is the default created by doccano export web application.

**Comment by abtExp** [comment]
The path issue, will push the fix today. Thanks for bringing this to my attention.

**Comment by abtExp** [comment]
Till then, a workaround would be to pass the exact path to the file like E:/dataset/.../annotations.jsonl

**Comment by abtExp** [comment]
Fixed in the new push.
